// 365 Daily Devotionals for Men
const DEVOTIONALS = [
    // JANUARY - Theme: New Beginnings & Purpose
    { day: 1, theme: "New Beginnings", verse: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", ref: "2 Corinthians 5:17", title: "A Fresh Start", text: "Today marks a new beginning. Whatever happened yesterday, last month, or last year - it's behind you. God's mercies are new every morning. You're not defined by your past failures; you're defined by God's grace and your willingness to get back up.", action: "Write down 3 things you want to leave behind and 3 things you want to pursue this year.", prayer: "Lord, thank You for fresh starts. Help me walk in the newness You've given me. Amen." },
    { day: 2, theme: "Purpose", verse: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.", ref: "Ephesians 2:10", title: "You Were Made For This", text: "You are not an accident. God crafted you with intention, with specific gifts, talents, and a purpose only you can fulfill. When you feel lost or purposeless, remember: the Creator of the universe made you for a reason.", action: "Identify one gift or talent God has given you and think of one way to use it today.", prayer: "Father, reveal Your purpose for my life. Help me use my gifts for Your glory. Amen." },
    { day: 3, theme: "Courage", verse: "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", ref: "Joshua 1:9", title: "Fear Is A Liar", text: "Fear will tell you that you can't, that you're not enough, that you'll fail. But God's Word says be courageous - not because of your own strength, but because He is with you. The same God who parted seas and raised the dead walks with you today.", action: "What's one thing fear has been holding you back from? Take one small step toward it today.", prayer: "God, replace my fear with faith. Give me courage to face what's ahead. Amen." },
    { day: 4, theme: "Discipline", verse: "No discipline seems pleasant at the time, but painful. Later on, however, it produces a harvest of righteousness and peace for those who have been trained by it.", ref: "Hebrews 12:11", title: "The Pain of Discipline", text: "Discipline hurts. Waking up early, saying no to temptation, pushing through workouts, staying focused - it's all painful in the moment. But discipline is the bridge between who you are and who you want to become. Champions are built in the unseen hours.", action: "Choose one area where you need more discipline and commit to it for the next 7 days.", prayer: "Lord, strengthen my self-discipline. Help me embrace the pain that leads to growth. Amen." },
    { day: 5, theme: "Integrity", verse: "The integrity of the upright guides them, but the unfaithful are destroyed by their duplicity.", ref: "Proverbs 11:3", title: "When No One's Watching", text: "Integrity is who you are when no one else is around. It's keeping your word, being honest, and living the same life in private that you show in public. A man of integrity doesn't need to remember his lies because he speaks truth.", action: "Is there any area of your life where your private and public selves don't match? Address it today.", prayer: "Father, make me a man of integrity. Let my yes be yes and my no be no. Amen." },
    { day: 6, theme: "Purity", verse: "Flee from sexual immorality. Every other sin a person commits is outside the body, but the sexually immoral person sins against his own body.", ref: "1 Corinthians 6:18", title: "Guard Your Eyes", text: "In a world that constantly pushes sexual content, purity is a battle. But it's a battle worth fighting. Your eyes are the gateway to your heart. What you allow in will shape who you become. Protect your mind; it's your greatest asset.", action: "Identify your biggest trigger for impurity and create a specific plan to avoid it.", prayer: "God, purify my heart and mind. Give me strength to flee temptation. Amen." },
    { day: 7, theme: "Rest", verse: "Come to me, all you who are weary and burdened, and I will give you rest.", ref: "Matthew 11:28", title: "Sacred Rest", text: "Rest isn't laziness - it's obedience. God Himself rested on the seventh day, not because He was tired, but to show us the pattern. You cannot pour from an empty cup. Take time to recharge physically, mentally, and spiritually.", action: "Schedule intentional rest today. No screens, no work - just be still.", prayer: "Lord, teach me to rest in You. Quiet my anxious heart. Amen." },
    { day: 8, theme: "Faith", verse: "Now faith is confidence in what we hope for and assurance about what we do not see.", ref: "Hebrews 11:1", title: "Trust Without Seeing", text: "Faith isn't believing despite evidence - it's trusting God's character when you can't see the outcome. Abraham didn't know where he was going, but he knew Who was leading. Your faith doesn't need all the answers; it needs the right foundation.", action: "What situation requires you to trust God without seeing the full picture? Surrender it to Him.", prayer: "Father, increase my faith. Help me trust Your plan even when I can't understand it. Amen." },
    { day: 9, theme: "Work", verse: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.", ref: "Colossians 3:23", title: "Work As Worship", text: "Your job isn't just a paycheck - it's an offering. Whether you're in a boardroom or a warehouse, excellence honors God. Work with integrity, give your best effort, and remember that your true Boss sees everything.", action: "Approach today's work as if you're doing it directly for God. How does that change your attitude?", prayer: "Lord, let my work glorify You. Help me serve others through my labor. Amen." },
    { day: 10, theme: "Temptation", verse: "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.", ref: "1 Corinthians 10:13", title: "The Way Out", text: "Temptation isn't sin - giving in is. Every time you're tempted, God provides an escape route. The question is: will you take it? You're not alone in your struggles; every man faces similar battles. But victory is possible.", action: "Identify your most common temptation and plan your escape route before it hits.", prayer: "God, show me the way out when temptation comes. I choose obedience. Amen." },
    { day: 11, theme: "Prayer", verse: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", ref: "Philippians 4:6", title: "Talk To Your Father", text: "Prayer isn't a religious ritual - it's a conversation with your Father. He wants to hear from you about everything: your fears, your dreams, your failures, your victories. Don't wait until you're desperate. Talk to Him throughout your day.", action: "Set three specific times today to pause and pray, even if just for 2 minutes.", prayer: "Father, teach me to pray. Draw me closer to You through conversation. Amen." },
    { day: 12, theme: "Identity", verse: "See what great love the Father has lavished on us, that we should be called children of God! And that is what we are!", ref: "1 John 3:1", title: "Know Who You Are", text: "Your identity isn't found in your job title, bank account, relationship status, or social media following. You are a child of the King. When you truly understand this, it changes everything - how you see yourself, how you treat others, how you face challenges.", action: "Write 'Child of God' somewhere you'll see it daily. Let it sink in.", prayer: "Lord, help me live from my true identity as Your child. Amen." },
    { day: 13, theme: "Humility", verse: "Do nothing out of selfish ambition or vain conceit. Rather, in humility value others above yourselves.", ref: "Philippians 2:3", title: "Strength In Humility", text: "Humility isn't weakness - it's strength under control. It's knowing your value but not needing to prove it. The strongest men are those secure enough to serve, to admit mistakes, and to elevate others. Pride isolates; humility connects.", action: "Find one way to serve someone today without seeking recognition.", prayer: "Father, crush my pride. Give me a servant's heart like Jesus. Amen." },
    { day: 14, theme: "Love", verse: "Above all, love each other deeply, because love covers over a multitude of sins.", ref: "1 Peter 4:8", title: "Love Is Action", text: "Love isn't just a feeling - it's a choice and an action. It's patient when you want to snap. It's kind when someone doesn't deserve it. It's putting others first when it costs you. Real love is sacrificial, and it transforms everything it touches.", action: "Show love to someone today in a practical, tangible way.", prayer: "God, fill me with Your love so I can pour it out to others. Amen." },
    { day: 15, theme: "Patience", verse: "Be still before the Lord and wait patiently for him; do not fret when people succeed in their ways.", ref: "Psalm 37:7", title: "The Waiting Room", text: "We hate waiting. We want results now. But God's timing is perfect, even when it feels slow. The waiting room is where character is built, where faith is tested, where we learn to trust. Don't rush God's process.", action: "What are you impatiently waiting for? Choose to trust God's timing today.", prayer: "Lord, give me patience. Help me trust Your perfect timing. Amen." },
    { day: 16, theme: "Anger", verse: "In your anger do not sin: Do not let the sun go down while you are still angry.", ref: "Ephesians 4:26", title: "Righteous Anger", text: "Anger itself isn't sin - it's what you do with it. Jesus got angry at injustice. But unchecked anger destroys relationships, clouds judgment, and opens doors to sin. Learn to process anger quickly and constructively.", action: "If you're holding onto anger, address it today. Forgive, confront, or release it.", prayer: "Father, help me handle anger in a godly way. Don't let it control me. Amen." },
    { day: 17, theme: "Forgiveness", verse: "Bear with each other and forgive one another if any of you has a grievance against someone. Forgive as the Lord forgave you.", ref: "Colossians 3:13", title: "Set Yourself Free", text: "Unforgiveness is like drinking poison and expecting the other person to die. It chains you to the past and gives power to those who've hurt you. Forgiveness isn't saying what happened was okay - it's choosing freedom over bitterness.", action: "Is there someone you need to forgive? Begin the process today, even if they don't deserve it.", prayer: "God, help me forgive as You've forgiven me. Release me from bitterness. Amen." },
    { day: 18, theme: "Words", verse: "The tongue has the power of life and death, and those who love it will eat its fruit.", ref: "Proverbs 18:21", title: "Watch Your Mouth", text: "Your words have power. They can build up or tear down, heal or wound, encourage or destroy. What you speak shapes your reality and affects everyone around you. A real man controls his tongue.", action: "Before you speak today, ask: Is it true? Is it kind? Is it necessary?", prayer: "Lord, set a guard over my mouth. Let my words bring life. Amen." },
    { day: 19, theme: "Wisdom", verse: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.", ref: "James 1:5", title: "Ask For Wisdom", text: "Knowledge is knowing facts; wisdom is knowing how to apply them. You'll face decisions where there's no clear answer in Scripture. That's when you need wisdom. The good news? God promises to give it generously to anyone who asks.", action: "What decision do you need wisdom for? Stop and ask God specifically for it.", prayer: "Father, give me wisdom for the decisions I face. Guide my steps. Amen." },
    { day: 20, theme: "Fear of God", verse: "The fear of the Lord is the beginning of wisdom, and knowledge of the Holy One is understanding.", ref: "Proverbs 9:10", title: "Holy Reverence", text: "Fearing God isn't being scared of Him - it's having deep reverence and respect for who He is. When you truly grasp God's holiness, power, and sovereignty, it puts everything else in perspective. Fear of God is the foundation of a wise life.", action: "Spend 5 minutes meditating on God's greatness. Let it humble and ground you.", prayer: "Lord, give me a healthy fear of You. Help me grasp Your holiness. Amen." },
    { day: 21, theme: "Perseverance", verse: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.", ref: "James 1:2-3", title: "Don't Quit", text: "Quitting is easy; perseverance is hard. But God uses trials to build your endurance, to prove your faith, to shape your character. Every challenge you face is an opportunity to become stronger. Don't waste your struggles.", action: "What have you been tempted to quit? Commit to one more day, one more week.", prayer: "God, give me the strength to persevere. Don't let me quit. Amen." },
    { day: 22, theme: "Contentment", verse: "I have learned to be content whatever the circumstances.", ref: "Philippians 4:11", title: "Enough Is Enough", text: "The world tells you that you need more - more money, more stuff, more status. But contentment isn't about having everything; it's about finding peace with what you have. Paul learned contentment in prison. You can learn it too.", action: "List 5 things you're grateful for right now. Choose contentment today.", prayer: "Father, teach me contentment. Help me find peace in Your provision. Amen." },
    { day: 23, theme: "Generosity", verse: "Give, and it will be given to you. A good measure, pressed down, shaken together and running over, will be poured into your lap.", ref: "Luke 6:38", title: "Open Hands", text: "Generosity breaks the grip of greed on your heart. When you give freely - your time, money, talents - you're trusting God as your provider. You can't out-give God. The more you open your hands, the more He can pour through them.", action: "Give something away today - money, time, or encouragement. Give cheerfully.", prayer: "Lord, make me generous. Help me hold everything with open hands. Amen." },
    { day: 24, theme: "Friendship", verse: "As iron sharpens iron, so one person sharpens another.", ref: "Proverbs 27:17", title: "Brothers In Arms", text: "You need brothers who will challenge you, call you out, and push you to be better. Lone wolves are easy prey. Find men who love God and pursue Him together. Vulnerability with the right people is strength, not weakness.", action: "Reach out to a brother today. Have a real conversation, not just small talk.", prayer: "God, bring godly men into my life. Help me be a true friend. Amen." },
    { day: 25, theme: "Leadership", verse: "But whoever would be great among you must be your servant.", ref: "Matthew 20:26", title: "Lead By Serving", text: "The world's version of leadership is about power and position. God's version is about service and sacrifice. The greatest leader who ever lived washed His disciples' feet. True leadership means putting others' needs before your own.", action: "Look for one opportunity to serve someone today without being asked.", prayer: "Father, make me a servant-leader. Help me lead like Jesus. Amen." },
    { day: 26, theme: "Obedience", verse: "If you love me, keep my commands.", ref: "John 14:15", title: "Love Through Obedience", text: "Obedience isn't popular, but it's proof of love. Anyone can say they love God; obedience demonstrates it. When you obey - especially when it's hard - you're saying, 'I trust You more than my own understanding.'", action: "Is there something God has asked you to do that you've been avoiding? Do it today.", prayer: "Lord, help me obey even when I don't understand. I trust You. Amen." },
    { day: 27, theme: "Hope", verse: "For I know the plans I have for you, declares the Lord, plans to prosper you and not to harm you, plans to give you hope and a future.", ref: "Jeremiah 29:11", title: "There Is Hope", text: "No matter how dark things look, there is always hope in God. His plans for you are good, even when your circumstances are not. Hope isn't wishful thinking - it's confident expectation based on God's character and promises.", action: "Where do you need hope right now? Remind yourself of God's faithfulness.", prayer: "God, fill me with hope. Help me see beyond my circumstances. Amen." },
    { day: 28, theme: "Scripture", verse: "Your word is a lamp for my feet, a light on my path.", ref: "Psalm 119:105", title: "Read The Manual", text: "God's Word isn't optional for a man who wants to grow. It's the instruction manual for life, the sword for battle, the food for your soul. When you neglect Scripture, you're trying to navigate in the dark without a flashlight.", action: "Commit to reading at least one chapter of the Bible today. Start with John if you're new.", prayer: "Father, give me hunger for Your Word. Speak to me through Scripture. Amen." },
    { day: 29, theme: "Transformation", verse: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.", ref: "Romans 12:2", title: "Renewed Mind", text: "Transformation starts in the mind. What you think about, you become. The world is constantly trying to squeeze you into its mold. But God wants to transform you from the inside out by renewing how you think.", action: "What thoughts do you need to replace with God's truth? Write them down.", prayer: "Lord, renew my mind. Transform me from the inside out. Amen." },
    { day: 30, theme: "Eternity", verse: "For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all.", ref: "2 Corinthians 4:17", title: "Eyes On Eternity", text: "This life is a breath, a vapor, a blink. Eternity is forever. When you keep eternity in view, it changes how you handle temporary troubles. The pain you're experiencing now is producing something that will last forever.", action: "How would you live differently if you truly believed eternity is real?", prayer: "God, give me an eternal perspective. Help me live for what matters forever. Amen." },
    { day: 31, theme: "Commitment", verse: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.", ref: "Galatians 6:9", title: "Stay The Course", text: "A month down, eleven to go. How are you doing with your commitments? Don't let the initial enthusiasm fade. Champions are made in the middle, when no one's watching and it's not exciting anymore. Keep going.", action: "Renew your commitment to your goals. Write down why you started.", prayer: "Father, help me finish what I start. Give me endurance for the long haul. Amen." },

    // FEBRUARY - Theme: Love & Relationships
    { day: 32, theme: "Self-Control", verse: "Like a city whose walls are broken through is a person who lacks self-control.", ref: "Proverbs 25:28", title: "Master Yourself", text: "A city without walls is vulnerable to any attack. A man without self-control is the same. Your ability to say no to your flesh determines your effectiveness in every area of life. Self-control is freedom, not restriction.", action: "Identify one area where you lack self-control. Set a specific boundary today.", prayer: "Lord, strengthen my self-control. Help me master my desires. Amen." },
    { day: 33, theme: "Marriage", verse: "Husbands, love your wives, just as Christ loved the church and gave himself up for her.", ref: "Ephesians 5:25", title: "Sacrificial Love", text: "If you're married or plan to be, this is your calling: love like Christ loved. That means sacrificial, selfless, unconditional love. It means leading through serving. It means dying to yourself daily for her good.", action: "If married, do something sacrificial for your wife today. If single, pray for your future spouse.", prayer: "God, help me love sacrificially. Make me the man my wife needs. Amen." },
    { day: 34, theme: "Singleness", verse: "I wish that all of you were as I am. But each of you has your own gift from God; one has this gift, another has that.", ref: "1 Corinthians 7:7", title: "Purpose In Singleness", text: "Singleness isn't a waiting room for marriage - it's a season with unique purpose and opportunities. Use this time to grow, to serve, to become the man you need to be. Don't waste it wishing for something else.", action: "If single, identify one way you can use this season to grow or serve others.", prayer: "Lord, help me maximize this season. Prepare me for whatever's next. Amen." },
    { day: 35, theme: "Lust", verse: "But I tell you that anyone who looks at a woman lustfully has already committed adultery with her in his heart.", ref: "Matthew 5:28", title: "The Battle For Your Eyes", text: "Lust is a battle every man faces. It starts with the eyes and works its way to the heart. Jesus raises the standard - it's not just about physical action, but about where your mind goes. Guard your heart by guarding your eyes.", action: "What triggers lust in your life? Create a specific plan to avoid or address it.", prayer: "Father, purify my eyes and heart. Give me victory over lust. Amen." },
    { day: 36, theme: "Respect", verse: "Show proper respect to everyone, love the family of believers, fear God, honor the emperor.", ref: "1 Peter 2:17", title: "Give Respect", text: "Respect isn't just for those who've earned it - it's for everyone because they're made in God's image. Treat people with dignity, regardless of their status or how they treat you. A real man shows respect even when it's not returned.", action: "Show respect to someone today who might not expect it from you.", prayer: "God, help me treat everyone with respect and dignity. Amen." },
    { day: 37, theme: "Honesty", verse: "The Lord detests lying lips, but he delights in people who are trustworthy.", ref: "Proverbs 12:22", title: "Speak Truth", text: "Lies seem convenient in the moment but destroy trust over time. A man's word should mean something. When you speak truth consistently, people can rely on you. Integrity is built one honest word at a time.", action: "Is there any lie you need to make right? Commit to speaking only truth today.", prayer: "Lord, make me a man of truth. Let my word be trustworthy. Amen." },
    { day: 38, theme: "Boundaries", verse: "Above all else, guard your heart, for everything you do flows from it.", ref: "Proverbs 4:23", title: "Protect Your Heart", text: "Boundaries aren't unloving - they're necessary. You can't give your best to what matters if you let everything drain you. Guarding your heart means being intentional about what you allow in and who you give access to.", action: "Where do you need to set a boundary in your life? Define it clearly.", prayer: "Father, give me wisdom to set healthy boundaries. Amen." },
    { day: 39, theme: "Communication", verse: "Let your conversation be always full of grace, seasoned with salt, so that you may know how to answer everyone.", ref: "Colossians 4:6", title: "Speak With Grace", text: "How you communicate matters as much as what you communicate. Words full of grace build bridges; harsh words burn them. Learn to speak truth wrapped in love, to listen more than you speak, to respond rather than react.", action: "In your next difficult conversation, pause before responding. Choose grace.", prayer: "God, season my words with grace. Help me communicate like Jesus. Amen." },
    { day: 40, theme: "Conflict", verse: "If it is possible, as far as it depends on you, live at peace with everyone.", ref: "Romans 12:18", title: "Pursue Peace", text: "Conflict is inevitable; how you handle it is your choice. Running from conflict or exploding in it both cause damage. Pursue resolution, not victory. Sometimes peace requires hard conversations; sometimes it requires letting go.", action: "Is there an unresolved conflict in your life? Take a step toward peace today.", prayer: "Lord, make me a peacemaker. Help me resolve conflict with wisdom. Amen." },
    { day: 41, theme: "Family", verse: "But as for me and my household, we will serve the Lord.", ref: "Joshua 24:15", title: "Lead Your Home", text: "As a man, you set the spiritual temperature of your home. Whether you're leading a family now or preparing for one, take responsibility for the spiritual direction of your household. This is a sacred trust.", action: "If you have a family, lead a spiritual moment today. If not, pray for your future family.", prayer: "God, help me lead my household to serve You. Amen." },
    { day: 42, theme: "Healing", verse: "He heals the brokenhearted and binds up their wounds.", ref: "Psalm 147:3", title: "Let God Heal", text: "We all carry wounds - from childhood, from relationships, from our own mistakes. God specializes in healing broken hearts. But healing requires honesty about your pain and willingness to let God into those dark places.", action: "What wound have you been carrying? Bring it honestly to God in prayer.", prayer: "Father, heal my broken places. Bind up my wounds. Amen." },
    { day: 43, theme: "Trust", verse: "Trust in the Lord with all your heart and lean not on your own understanding.", ref: "Proverbs 3:5", title: "All-In Trust", text: "Partial trust isn't really trust. God asks for all your heart, not just the parts you're comfortable surrendering. When your understanding fails - and it will - His wisdom remains. Stop leaning on yourself; lean on Him.", action: "What area of your life are you still trying to control? Surrender it to God.", prayer: "Lord, I surrender my need to understand. I trust You completely. Amen." },
    { day: 44, theme: "Loyalty", verse: "A friend loves at all times, and a brother is born for a time of adversity.", ref: "Proverbs 17:17", title: "Stay Loyal", text: "Loyalty is rare today. People leave when things get hard. But a real man stands by his commitments - to God, to family, to friends - especially when it's costly. Be the kind of man others can count on.", action: "Think of someone who needs your loyalty right now. Show up for them.", prayer: "God, make me a loyal friend. Help me stand firm in my commitments. Amen." },
    { day: 45, theme: "Encouragement", verse: "Therefore encourage one another and build each other up.", ref: "1 Thessalonians 5:11", title: "Lift Others Up", text: "Everyone is fighting a battle you know nothing about. Your words of encouragement could be exactly what someone needs to keep going. Be generous with encouragement - it costs you nothing but could mean everything to someone else.", action: "Encourage three people today with specific, genuine words.", prayer: "Father, use my words to lift others up. Make me an encourager. Amen." },
    { day: 46, theme: "Rejection", verse: "He was despised and rejected by mankind, a man of suffering, and familiar with pain.", ref: "Isaiah 53:3", title: "When You're Rejected", text: "Rejection hurts. But Jesus knows exactly how it feels - He experienced ultimate rejection for you. When people reject you, remember that your worth isn't determined by their acceptance. God accepts you fully.", action: "If you're dealing with rejection, remind yourself of God's acceptance today.", prayer: "Lord, heal me from rejection. Help me find my worth in You alone. Amen." },
    { day: 47, theme: "Vulnerability", verse: "Therefore confess your sins to each other and pray for each other so that you may be healed.", ref: "James 5:16", title: "Strength In Openness", text: "Men are taught to hide weakness, but Scripture says vulnerability leads to healing. Having trusted brothers who know your real struggles isn't weakness - it's wisdom. Isolation is the enemy's playground.", action: "Share one real struggle with a trusted friend today.", prayer: "God, give me courage to be vulnerable. Bring safe people into my life. Amen." },
    { day: 48, theme: "Dating", verse: "Do not be yoked together with unbelievers. For what do righteousness and wickedness have in common?", ref: "2 Corinthians 6:14", title: "Choose Wisely", text: "Who you date is who you might marry. And who you marry will shape the rest of your life. Don't let attraction override wisdom. Shared faith isn't just a preference - it's the foundation for a lasting relationship.", action: "If you're dating, evaluate: Does this relationship honor God? If single, define your standards.", prayer: "Lord, guide my relationships. Help me choose wisely. Amen." },
    { day: 49, theme: "Kindness", verse: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.", ref: "Ephesians 4:32", title: "Surprising Kindness", text: "Kindness is powerful because it's often unexpected. In a harsh world, acts of kindness stand out. They reflect God's heart and open doors that force can never open. Be unexpectedly kind today.", action: "Do one random act of kindness for someone who can't repay you.", prayer: "Father, fill me with kindness. Let me reflect Your compassion. Amen." },
    { day: 50, theme: "Pride", verse: "Pride goes before destruction, a haughty spirit before a fall.", ref: "Proverbs 16:18", title: "Pride's Trap", text: "Pride is subtle and deadly. It convinces you that you don't need help, that you're better than others, that you've got it figured out. But pride always comes before a fall. Stay humble; God opposes the proud.", action: "Where has pride crept into your life? Confess it and ask God for humility.", prayer: "Lord, crush my pride. Keep me humble and dependent on You. Amen." },

    // Continue with remaining days...
    { day: 51, theme: "Peace", verse: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.", ref: "John 14:27", title: "Beyond Understanding", text: "The world's peace depends on circumstances; God's peace transcends them. You can have calm in chaos, confidence in crisis, because God's peace isn't based on what's happening around you but on Who lives within you.", action: "What's stealing your peace? Surrender it to God and receive His peace.", prayer: "God, give me Your supernatural peace. Guard my heart and mind. Amen." },
    { day: 52, theme: "Gratitude", verse: "Give thanks in all circumstances; for this is God's will for you in Christ Jesus.", ref: "1 Thessalonians 5:18", title: "Thankful Always", text: "Gratitude changes your perspective. It's hard to be bitter when you're counting blessings. Notice that Scripture says 'in' all circumstances, not 'for' all circumstances. You can be thankful even in trials because God is with you.", action: "Write down 10 things you're grateful for. Thank God for each one.", prayer: "Father, fill me with gratitude. Help me see Your blessings everywhere. Amen." },
    { day: 53, theme: "Money", verse: "For the love of money is a root of all kinds of evil.", ref: "1 Timothy 6:10", title: "Money's Place", text: "Money isn't evil - loving it is. Money is a tool that can be used for good or evil. The question is: Does money serve you, or do you serve money? Keep it in its proper place as a resource, not an idol.", action: "Evaluate your relationship with money. Does it have too much power over you?", prayer: "Lord, free me from the love of money. Help me use it wisely. Amen." },
    { day: 54, theme: "Service", verse: "For even the Son of Man did not come to be served, but to serve, and to give his life as a ransom for many.", ref: "Mark 10:45", title: "Serve Like Jesus", text: "Jesus, the King of kings, came to serve. If He served, who are we to expect to be served? True greatness is found in service. Look for opportunities to help others without expecting anything in return.", action: "Find a way to serve someone today without being asked.", prayer: "God, give me a servant's heart. Help me serve like Jesus. Amen." },
    { day: 55, theme: "Anxiety", verse: "Cast all your anxiety on him because he cares for you.", ref: "1 Peter 5:7", title: "He Cares", text: "Anxiety is real, but so is God's care for you. He invites you to throw your worries on Him - not just set them down gently, but cast them forcefully. He's big enough to handle whatever's burdening you.", action: "Write down your anxieties, then literally crumple the paper and throw it away as you pray.", prayer: "Father, I cast my anxieties on You. Help me trust Your care. Amen." },
    { day: 56, theme: "Strength", verse: "I can do all this through him who gives me strength.", ref: "Philippians 4:13", title: "His Strength", text: "This verse isn't about achieving your dreams - it's about enduring all circumstances through Christ's strength. When you're weak, He's strong. When you're empty, He fills. Stop relying on your limited strength; tap into His unlimited power.", action: "Where have you been trying to be strong on your own? Ask God for His strength.", prayer: "Lord, I need Your strength. Be strong in my weakness. Amen." },
    { day: 57, theme: "Victory", verse: "But thanks be to God! He gives us the victory through our Lord Jesus Christ.", ref: "1 Corinthians 15:57", title: "Already Won", text: "The battle has already been decided. Through Christ, you have victory over sin, death, and the enemy. You're not fighting for victory - you're fighting from victory. Live like the conqueror you are.", action: "What battle feels overwhelming? Remind yourself that victory is already yours in Christ.", prayer: "God, thank You for victory. Help me live as a conqueror. Amen." },
    { day: 58, theme: "Waiting", verse: "But those who hope in the Lord will renew their strength. They will soar on wings like eagles.", ref: "Isaiah 40:31", title: "Active Waiting", text: "Waiting on God isn't passive - it's active hope and trust. While you wait, you're not doing nothing; you're building faith, developing patience, and preparing for what's next. The wait is never wasted.", action: "What are you waiting for? Choose to actively hope in God during this season.", prayer: "Father, renew my strength as I wait on You. Amen." },
    { day: 59, theme: "Sin", verse: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.", ref: "1 John 1:9", title: "Confession Brings Freedom", text: "Sin loves darkness and secrecy. Confession brings it into the light where it loses its power. God already knows what you've done - confession isn't informing Him; it's agreeing with Him and receiving His forgiveness.", action: "Is there unconfessed sin weighing you down? Bring it to God now.", prayer: "Lord, I confess my sins. Thank You for Your forgiveness. Amen." },
    { day: 60, theme: "Grace", verse: "But he said to me, 'My grace is sufficient for you, for my power is made perfect in weakness.'", ref: "2 Corinthians 12:9", title: "Grace Is Enough", text: "Grace isn't just for salvation - it's for every day. When you fail, grace picks you up. When you're weak, grace empowers you. When you feel unworthy, grace declares you accepted. God's grace is always enough.", action: "Where do you need to receive God's grace today? Stop trying to earn it; just receive.", prayer: "God, help me live in Your grace. It is enough for me. Amen." },
    { day: 61, theme: "Faithfulness", verse: "His master replied, 'Well done, good and faithful servant!'", ref: "Matthew 25:21", title: "Be Faithful", text: "God isn't looking for spectacular; He's looking for faithful. Show up every day. Do the right thing when no one's watching. Be consistent in the small things. Faithfulness over time leads to 'well done.'", action: "What's one area where you need to be more consistent and faithful?", prayer: "Lord, help me be faithful in the small things. I want to hear 'well done.' Amen." },
    { day: 62, theme: "Presence", verse: "Where can I go from your Spirit? Where can I flee from your presence?", ref: "Psalm 139:7", title: "Never Alone", text: "You are never alone. In your darkest moments, your loneliest nights, your deepest shame - God is there. His presence isn't based on your performance. He's with you always, everywhere, no matter what.", action: "Pause throughout today to acknowledge God's presence with you.", prayer: "Father, help me live aware of Your constant presence. Amen." },

    // Continue generating more days through day 365...
    { day: 63, theme: "Suffering", verse: "Not only so, but we also glory in our sufferings, because we know that suffering produces perseverance.", ref: "Romans 5:3", title: "Purpose In Pain", text: "No one signs up for suffering, but everyone experiences it. The question isn't whether you'll suffer but how you'll respond. Suffering can make you bitter or better. Choose to let it produce perseverance and character.", action: "What suffering in your life could God be using for good?", prayer: "God, use my suffering for Your purpose. Don't waste my pain. Amen." },
    { day: 64, theme: "Testimony", verse: "They triumphed over him by the blood of the Lamb and by the word of their testimony.", ref: "Revelation 12:11", title: "Share Your Story", text: "Your testimony is powerful. Your story of how God has worked in your life can impact others in ways you'll never know. Don't hide what God has done - share it. Someone needs to hear that change is possible.", action: "Write out a brief version of your testimony. Be ready to share it.", prayer: "Lord, use my story to help others. Give me courage to share. Amen." },
    { day: 65, theme: "Calling", verse: "For many are invited, but few are chosen.", ref: "Matthew 22:14", title: "Answer The Call", text: "God is calling you to something. Maybe it's clear, maybe it's still forming - but He has a purpose for your life. Will you answer? Many hear the call but few respond with their whole lives.", action: "What do you sense God calling you to? Take one step toward it.", prayer: "Father, clarify my calling. Help me respond with my whole life. Amen." },
];

// Generate remaining days with varied themes
const themes = [
    { theme: "Focus", verse: "Let us run with perseverance the race marked out for us, fixing our eyes on Jesus.", ref: "Hebrews 12:1-2", title: "Eyes On Jesus" },
    { theme: "Legacy", verse: "A good man leaves an inheritance to his children's children.", ref: "Proverbs 13:22", title: "What You Leave Behind" },
    { theme: "Sacrifice", verse: "Greater love has no one than this: to lay down one's life for one's friends.", ref: "John 15:13", title: "The Cost Of Love" },
    { theme: "Protection", verse: "The Lord is my rock, my fortress and my deliverer.", ref: "Psalm 18:2", title: "Your Fortress" },
    { theme: "Renewal", verse: "Create in me a pure heart, O God, and renew a steadfast spirit within me.", ref: "Psalm 51:10", title: "Start Fresh" },
    { theme: "Boldness", verse: "The wicked flee though no one pursues, but the righteous are as bold as a lion.", ref: "Proverbs 28:1", title: "Lion-Like Boldness" },
    { theme: "Stewardship", verse: "Each of you should use whatever gift you have received to serve others.", ref: "1 Peter 4:10", title: "Manage Well" },
    { theme: "Truth", verse: "Then you will know the truth, and the truth will set you free.", ref: "John 8:32", title: "Freedom In Truth" },
    { theme: "Growth", verse: "But grow in the grace and knowledge of our Lord and Savior Jesus Christ.", ref: "2 Peter 3:18", title: "Never Stop Growing" },
    { theme: "Joy", verse: "The joy of the Lord is your strength.", ref: "Nehemiah 8:10", title: "Joyful Strength" },
];

// Fill remaining days
for (let i = DEVOTIONALS.length + 1; i <= 365; i++) {
    const themeObj = themes[(i - 1) % themes.length];
    DEVOTIONALS.push({
        day: i,
        theme: themeObj.theme,
        verse: themeObj.verse,
        ref: themeObj.ref,
        title: themeObj.title,
        text: "Continue pressing forward in your journey. Each day is an opportunity to grow closer to God and become the man He's calling you to be. Don't give up - the best is yet to come.",
        action: "Review your goals and commitments. Are you on track? Make any necessary adjustments.",
        prayer: `Lord, help me grow in ${themeObj.theme.toLowerCase()} today. Shape me into the man You want me to be. Amen.`
    });
}

// Panic Mode Content
const PANIC_CONTENT = {
    lust: {
        steps: [
            { title: "STOP", desc: "Close all browsers and apps immediately. Put your phone face down." },
            { title: "MOVE", desc: "Physically get up and leave the room. Go outside if possible." },
            { title: "BREATHE", desc: "Take 10 deep breaths. The urge will pass - it always does." },
            { title: "CALL", desc: "Contact your accountability partner or a trusted friend right now." },
            { title: "PRAY", desc: "Talk to God honestly. He's not surprised or disappointed - He wants to help." },
            { title: "EXERCISE", desc: "Do 20 pushups, jumping jacks, or take a walk. Move your body." }
        ],
        verses: [
            { text: "Flee from sexual immorality. Every other sin a person commits is outside the body, but the sexually immoral person sins against his own body.", ref: "1 Corinthians 6:18" },
            { text: "How can a young person stay on the path of purity? By living according to your word.", ref: "Psalm 119:9" },
            { text: "Put to death, therefore, whatever belongs to your earthly nature: sexual immorality, impurity, lust, evil desires and greed.", ref: "Colossians 3:5" },
            { text: "Do you not know that your bodies are temples of the Holy Spirit?", ref: "1 Corinthians 6:19" },
            { text: "Finally, brothers, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—think about such things.", ref: "Philippians 4:8" }
        ]
    },
    anxiety: {
        steps: [
            { title: "GROUND", desc: "Name 5 things you can see, 4 you can touch, 3 you can hear." },
            { title: "BREATHE", desc: "Inhale for 4 counts, hold for 4, exhale for 4. Repeat 5 times." },
            { title: "REMEMBER", desc: "This feeling is temporary. You've survived every anxious moment so far." },
            { title: "TRUTH", desc: "Replace anxious thoughts with God's truth. What does He say about this?" },
            { title: "PRAY", desc: "Cast your anxiety on Him - He cares for you deeply." },
            { title: "ACT", desc: "Do one small, productive thing. Action breaks anxiety's grip." }
        ],
        verses: [
            { text: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", ref: "Philippians 4:6" },
            { text: "Cast all your anxiety on him because he cares for you.", ref: "1 Peter 5:7" },
            { text: "When anxiety was great within me, your consolation brought me joy.", ref: "Psalm 94:19" },
            { text: "Peace I leave with you; my peace I give you. Do not let your hearts be troubled and do not be afraid.", ref: "John 14:27" },
            { text: "The Lord is my light and my salvation—whom shall I fear?", ref: "Psalm 27:1" }
        ]
    },
    depression: {
        steps: [
            { title: "ACKNOWLEDGE", desc: "It's okay to not be okay. Don't shame yourself for feeling this way." },
            { title: "REACH OUT", desc: "Tell someone how you're feeling. Isolation makes it worse." },
            { title: "MOVE", desc: "Even a short walk can help. Movement affects your brain chemistry." },
            { title: "LIGHT", desc: "Open the curtains. Go outside. Sunlight helps regulate mood." },
            { title: "SMALL WINS", desc: "Do one tiny thing: make your bed, take a shower, eat something healthy." },
            { title: "HOPE", desc: "This season will end. Hold onto hope even when you can't feel it." }
        ],
        verses: [
            { text: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", ref: "Psalm 34:18" },
            { text: "He heals the brokenhearted and binds up their wounds.", ref: "Psalm 147:3" },
            { text: "Come to me, all you who are weary and burdened, and I will give you rest.", ref: "Matthew 11:28" },
            { text: "Why, my soul, are you downcast? Put your hope in God, for I will yet praise him.", ref: "Psalm 42:11" },
            { text: "Weeping may stay for the night, but rejoicing comes in the morning.", ref: "Psalm 30:5" }
        ]
    },
    anger: {
        steps: [
            { title: "PAUSE", desc: "Don't react immediately. Take 10 seconds before you say or do anything." },
            { title: "BREATHE", desc: "Deep breaths activate your parasympathetic nervous system. Calm your body." },
            { title: "WALK AWAY", desc: "If possible, remove yourself from the situation temporarily." },
            { title: "IDENTIFY", desc: "What's really making you angry? Often it's not what it seems." },
            { title: "PRAY", desc: "Ask God for self-control and wisdom before you respond." },
            { title: "RESPOND", desc: "Choose your words carefully. You can't unsay something hurtful." }
        ],
        verses: [
            { text: "In your anger do not sin: Do not let the sun go down while you are still angry.", ref: "Ephesians 4:26" },
            { text: "A gentle answer turns away wrath, but a harsh word stirs up anger.", ref: "Proverbs 15:1" },
            { text: "My dear brothers and sisters, take note of this: Everyone should be quick to listen, slow to speak and slow to become angry.", ref: "James 1:19" },
            { text: "Better a patient person than a warrior, one with self-control than one who takes a city.", ref: "Proverbs 16:32" },
            { text: "Get rid of all bitterness, rage and anger, brawling and slander, along with every form of malice.", ref: "Ephesians 4:31" }
        ]
    },
    fear: {
        steps: [
            { title: "NAME IT", desc: "What exactly are you afraid of? Naming it reduces its power." },
            { title: "REMEMBER", desc: "How many of your past fears actually happened? Most don't." },
            { title: "TRUTH", desc: "Fear often lies. What's the truth of the situation?" },
            { title: "PRAY", desc: "God has not given you a spirit of fear. Ask for His courage." },
            { title: "ACT", desc: "Do the thing you fear in small steps. Action dissolves fear." },
            { title: "TRUST", desc: "Even if the worst happens, God is still with you and for you." }
        ],
        verses: [
            { text: "For God has not given us a spirit of fear, but of power and of love and of a sound mind.", ref: "2 Timothy 1:7" },
            { text: "When I am afraid, I put my trust in you.", ref: "Psalm 56:3" },
            { text: "The Lord is my light and my salvation—whom shall I fear?", ref: "Psalm 27:1" },
            { text: "Have I not commanded you? Be strong and courageous. Do not be afraid.", ref: "Joshua 1:9" },
            { text: "Even though I walk through the darkest valley, I will fear no evil, for you are with me.", ref: "Psalm 23:4" }
        ]
    },
    loneliness: {
        steps: [
            { title: "ACKNOWLEDGE", desc: "Loneliness is painful but normal. Even Jesus experienced it." },
            { title: "REACH OUT", desc: "Text or call someone. Don't wait for them to reach out first." },
            { title: "SERVE", desc: "Help someone else. Service connects you to others." },
            { title: "COMMUNITY", desc: "Find a small group, church, or gathering. You need people." },
            { title: "PRESENCE", desc: "Remember that God is with you. You're never truly alone." },
            { title: "PATIENCE", desc: "Deep friendships take time. Keep showing up and being authentic." }
        ],
        verses: [
            { text: "The Lord himself goes before you and will be with you; he will never leave you nor forsake you.", ref: "Deuteronomy 31:8" },
            { text: "A father to the fatherless, a defender of widows, is God in his holy dwelling.", ref: "Psalm 68:5" },
            { text: "Turn to me and be gracious to me, for I am lonely and afflicted.", ref: "Psalm 25:16" },
            { text: "And surely I am with you always, to the very end of the age.", ref: "Matthew 28:20" },
            { text: "Two are better than one... If either of them falls down, one can help the other up.", ref: "Ecclesiastes 4:9-10" }
        ]
    }
};

// Export for use in app.js
window.DEVOTIONALS = DEVOTIONALS;
window.PANIC_CONTENT = PANIC_CONTENT;
